name: Continuous Integration

on:
  push:
    branches:
      - main

jobs:
  merge_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name : list dir
        run : ls
        
      - name: change directory
        run: cd decentralizedVotingUsingBlockchain
      
      - name : list dir
        run : ls
        
      - name: Install dependencies
        run: npm install --force

      - name: Build application
        run: npm run start
